//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Generator generates CLI command files
type Generator struct {
	outputDir string
}

// NewGenerator creates a new generator
func NewGenerator(outputDir string) *Generator {
	return &Generator{outputDir: outputDir}
}

// GenerateService generates a command file for a service
func (g *Generator) GenerateService(svc *Service) error {
	tmpl := template.Must(template.New("service").Funcs(templateFuncs).Parse(serviceTemplate))

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, svc); err != nil {
		return fmt.Errorf("template execution failed: %w", err)
	}

	// Format the generated code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Write unformatted for debugging
		outPath := filepath.Join(g.outputDir, svc.Name+".go.broken")
		os.WriteFile(outPath, buf.Bytes(), 0644)
		return fmt.Errorf("go format failed: %w (written to %s)", err, outPath)
	}

	outPath := filepath.Join(g.outputDir, svc.Name+".go")
	return os.WriteFile(outPath, formatted, 0644)
}

// GenerateRegistry generates the registry file that wires all services
func (g *Generator) GenerateRegistry(services []*Service) error {
	tmpl := template.Must(template.New("registry").Funcs(templateFuncs).Parse(registryTemplate))

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, services); err != nil {
		return fmt.Errorf("template execution failed: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		outPath := filepath.Join(g.outputDir, "registry.go.broken")
		os.WriteFile(outPath, buf.Bytes(), 0644)
		return fmt.Errorf("go format failed: %w", err)
	}

	outPath := filepath.Join(g.outputDir, "registry.go")
	return os.WriteFile(outPath, formatted, 0644)
}

var templateFuncs = template.FuncMap{
	"lower":      strings.ToLower,
	"upper":      strings.ToUpper,
	"title":      strings.Title,
	"kebab":      toKebabCase,
	"camel":      toCamelCase,
	"pascalCase": toPascalCase,
	"quote":      func(s string) string { return fmt.Sprintf("%q", s) },
	"hasPrefix":  strings.HasPrefix,
}

func toKebabCase(s string) string {
	return strings.ReplaceAll(strings.ToLower(s), "_", "-")
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i := 0; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

// serviceTemplate is the template for generating service command files
const serviceTemplate = `// Code generated by acscli/tools/generate. DO NOT EDIT.

package generated

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
	"github.com/stackrox/rox/acscli/internal/client"
	"github.com/stackrox/rox/acscli/internal/fieldmask"
)

// New{{.Name | pascalCase}}Cmd creates the {{.Name}} service command
func New{{.Name | pascalCase}}Cmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "{{.Name}}",
		Short: "{{.DisplayName}} service operations",
		Long:  "Operations for the {{.DisplayName}} service.\n\nUse 'acs schema {{.Name}}' to see available methods.",
	}

{{range .Methods}}
	cmd.AddCommand(new{{$.Name | pascalCase}}{{.Name | pascalCase}}Cmd())
{{end}}

	return cmd
}

{{range .Methods}}
func new{{$.Name | pascalCase}}{{.Name | pascalCase}}Cmd() *cobra.Command {
	var (
{{range .Parameters}}
		flag{{.VarName | pascalCase}} {{.GoType}}
{{end}}
{{if .HasBody}}
		jsonInput string
{{end}}
		dryRun    bool
		outputFmt string
		fields    string
	)

	cmd := &cobra.Command{
		Use:   "{{.Name | lower}}",
		Short: "{{if .Description}}{{.Description}}{{else}}{{.DisplayName}}{{end}}",
		Long:  "{{if .Description}}{{.Description}}\n\n{{end}}HTTP: {{.HTTPMethod}} {{.Path}}",
		RunE: func(cmd *cobra.Command, args []string) error {
			// Build request
			cfg := client.Config{
				Endpoint: os.Getenv("ROX_ENDPOINT"),
				Token:    os.Getenv("ROX_API_TOKEN"),
				Insecure: os.Getenv("ROX_INSECURE") == "true",
			}

			c, err := client.NewClient(cfg)
			if err != nil {
				return err
			}

			// Build path with path parameters
			path := "{{.Path}}"
{{range .Parameters}}
{{if eq .Location "path"}}
			path = strings.ReplaceAll(path, "{{"{"}}{{.Name}}{{"}"}}", fmt.Sprintf("%v", flag{{.VarName | pascalCase}}))
{{end}}
{{end}}

			// Build query parameters
			var queryParams []string
{{range .Parameters}}
{{if eq .Location "query"}}
{{if eq .GoType "string"}}
			if flag{{.VarName | pascalCase}} != "" {
				queryParams = append(queryParams, fmt.Sprintf("{{.Name}}=%s", flag{{.VarName | pascalCase}}))
			}
{{else if eq .GoType "bool"}}
			if flag{{.VarName | pascalCase}} {
				queryParams = append(queryParams, fmt.Sprintf("{{.Name}}=%v", flag{{.VarName | pascalCase}}))
			}
{{else}}
			if flag{{.VarName | pascalCase}} != 0 {
				queryParams = append(queryParams, fmt.Sprintf("{{.Name}}=%v", flag{{.VarName | pascalCase}}))
			}
{{end}}
{{end}}
{{end}}
			if len(queryParams) > 0 {
				path = path + "?" + strings.Join(queryParams, "&")
			}

			// Handle dry-run
			if dryRun {
				result := map[string]interface{}{
					"dry_run":     true,
					"method":      "{{.HTTPMethod}}",
					"path":        path,
{{if .HasBody}}
					"has_body":    true,
					"body_source": jsonInput,
{{end}}
				}
				return outputResult(result, outputFmt)
			}

			// Make request
			var resp []byte
{{if .HasBody}}
			var body interface{}
			if jsonInput != "" {
				if strings.HasPrefix(jsonInput, "@") {
					data, err := os.ReadFile(strings.TrimPrefix(jsonInput, "@"))
					if err != nil {
						return fmt.Errorf("failed to read JSON file: %w", err)
					}
					if err := json.Unmarshal(data, &body); err != nil {
						return fmt.Errorf("invalid JSON in file: %w", err)
					}
				} else {
					if err := json.Unmarshal([]byte(jsonInput), &body); err != nil {
						return fmt.Errorf("invalid JSON: %w", err)
					}
				}
			}
{{if eq .HTTPMethod "POST"}}
			resp, err = c.Post(path, body)
{{else if eq .HTTPMethod "PUT"}}
			resp, err = c.Put(path, body)
{{else if eq .HTTPMethod "PATCH"}}
			resp, err = c.Request("PATCH", path, body)
{{else}}
			resp, err = c.Get(path)
{{end}}
{{else}}
{{if eq .HTTPMethod "DELETE"}}
			resp, err = c.Delete(path)
{{else}}
			resp, err = c.Get(path)
{{end}}
{{end}}
			if err != nil {
				return err
			}

			// Apply field mask if specified
			if fields != "" {
				resp, err = fieldmask.Apply(resp, fields)
				if err != nil {
					return fmt.Errorf("failed to apply field mask: %w", err)
				}
			}

			// Parse and output response
			var result interface{}
			if err := json.Unmarshal(resp, &result); err != nil {
				// Return raw response if not JSON
				fmt.Println(string(resp))
				return nil
			}

			return outputResult(result, outputFmt)
		},
	}

	// Add flags
{{range .Parameters}}
{{if eq .GoType "string"}}
	cmd.Flags().StringVar(&flag{{.VarName | pascalCase}}, "{{.FlagName}}", "", {{.Description | quote}})
{{else if eq .GoType "int"}}
	cmd.Flags().IntVar(&flag{{.VarName | pascalCase}}, "{{.FlagName}}", 0, {{.Description | quote}})
{{else if eq .GoType "int32"}}
	cmd.Flags().Int32Var(&flag{{.VarName | pascalCase}}, "{{.FlagName}}", 0, {{.Description | quote}})
{{else if eq .GoType "int64"}}
	cmd.Flags().Int64Var(&flag{{.VarName | pascalCase}}, "{{.FlagName}}", 0, {{.Description | quote}})
{{else if eq .GoType "bool"}}
	cmd.Flags().BoolVar(&flag{{.VarName | pascalCase}}, "{{.FlagName}}", false, {{.Description | quote}})
{{else if eq .GoType "float64"}}
	cmd.Flags().Float64Var(&flag{{.VarName | pascalCase}}, "{{.FlagName}}", 0, {{.Description | quote}})
{{else}}
	cmd.Flags().StringVar(&flag{{.VarName | pascalCase}}, "{{.FlagName}}", "", {{.Description | quote}})
{{end}}
{{if .Required}}
	cmd.MarkFlagRequired("{{.FlagName}}")
{{end}}
{{end}}

{{if .HasBody}}
	cmd.Flags().StringVar(&jsonInput, "json", "", "JSON request body (use @filename to read from file)")
{{end}}
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Preview request without executing")
	cmd.Flags().StringVarP(&outputFmt, "output", "o", "", "Output format: json, table (default: auto)")
	cmd.Flags().StringVar(&fields, "fields", "", "Comma-separated fields to include (e.g., id,name,policies[].severity)")

	return cmd
}

{{end}}
`

// registryTemplate generates the file that registers all service commands
const registryTemplate = `// Code generated by acscli/tools/generate. DO NOT EDIT.

package generated

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

// RegisterCommands adds all generated service commands to the root command
func RegisterCommands(root *cobra.Command) {
{{range .}}
	root.AddCommand(New{{.Name | pascalCase}}Cmd())
{{end}}
}

// ServiceNames returns all available service names
func ServiceNames() []string {
	return []string{
{{range .}}
		"{{.Name}}",
{{end}}
	}
}

// outputResult handles output formatting
func outputResult(result interface{}, format string) error {
	// Auto-detect format based on TTY
	if format == "" {
		if fileInfo, _ := os.Stdout.Stat(); (fileInfo.Mode() & os.ModeCharDevice) != 0 {
			format = "json" // Use JSON with pretty-print for TTY
		} else {
			format = "json"
		}
	}

	switch format {
	case "json":
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(result)
	case "table":
		// For table output, try to format as key-value or list
		data, _ := json.MarshalIndent(result, "", "  ")
		fmt.Println(string(data))
		return nil
	default:
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(result)
	}
}
`
