# permissions for end users to edit stackroxresults.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: results-controller
    app.kubernetes.io/managed-by: kustomize
  name: stackroxresults-editor-role
rules:
- apiGroups:
  - platform.stackrox.io
  resources:
  - stackroxresults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.stackrox.io
  resources:
  - stackroxresults/status
  verbs:
  - get